apiVersion: v1
kind: Service
metadata:
  name: users-service
spec: 
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP 
      #포트는 같은 포트를 사용하는것이 일반적 다른 포트를 사용할 수도 있음
      port: 8080 #외부를 향하는 포트, 즉 요청을 보낼 수 있는 이 service IP 주소의 포트
      targetPort: 8080 #요청이 전달될 컨테이너 내부의, Pod 내부의 포트